"""这里存放了所有调用的在线api的数据"""
[chat]
base_url = "https://api.moonshot.cn/v1"
model_id = "kimi-k2-0905-preview"
api_key = "sk-1rvrHMciynw0PiW4vDjWAYkbONnmikGnsHI7tSRTv1FtiL1Q"
vision = true

[vision]
base_url = "" 
api_key = ""

[tts]
base_url = ""
api_key = ""

[rag]
host = "127.0.0.1"
api_key = ""

[search]
platform = "Tavily"
base_url = ""
api_key = ""
